### ISSUE TITLE
실제 시연시 RDS 포기하고 개인로컬 MySQL DB 사용해야 할 것 같습니다.

### ISSUE THREAD

**Issue by Hyeon9mak** [wogns7534/Project3#31]
개발 편의를 위해서 RDS를 사용하고 있었는데,
RDS 실제 위치가 **미국 알오하** 쪽에 위치하다보니
페이지 동작이 굉장히 느린 것이 확인되었습니다.

우선 당장 개발단계에서는 편의를 위해 현 상태를 유지하고
추후 시연영상 녹화단계에서는 **개인 로컬 DB**를 이용하는 것으로 해야할 것 같습니다.
의견 제시 부탁드립니다.

**Comment by pdache** [comment]
우선 RDS로 진행 후 시연 단계 전에 MySQL로 전환하면 될 것 같네요

**Comment by Hyeon9mak** [comment]
계획대로 진행 완료.
