### ISSUE TITLE
3차 프로젝트 템플릿 결정

### ISSUE THREAD

**Issue by wlsgh6346** [wogns7534/Project3#6]
각자 원하는 템플릿이나 적절하다고 생각하는 템플릿 올려주세요

**Comment by Hyeon9mak** [comment]
https://colorlib.com/demo?theme=eshop

https://colorlib.com/preview/#persuit

https://colorlib.com/preview/#ogani

https://colorlib.com/preview/#winter

4 가지 찾아봤음. 확인해보고 선택

**Comment by wlsgh6346** [comment]
https://colorlib.com/demo?theme=eshop
https://colorlib.com/preview/#ogani

이거 2개가 깔끔하게 카테고리도 단순화시키기 좋아서 좋음

**Comment by pdache** [comment]
https://colorlib.com/demo?theme=eshop
https://colorlib.com/preview/#winter

1번, 4번이 적합한 것 같다는 판단이 들었습니다.

**Comment by pdache** [comment]
1번과 3번을 조합하여 구성하면 좋을 것 같습니다.

**Comment by Hyeon9mak** [comment]
@wlsgh6346 @pdache 
그럼 eshop 템플릿과 ogani 템플릿 압축파일 리퀘스트 올리겠습니다. 확인댓글 달아주세요.
